spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: "super-secret-key-must-be-very-long-to-be-secure-enough-for-hs256"
  expiration: 1h

auth:
  refresh-token:
    expiration: 14d
    cookie-name: refresh_token

logging:
  level:
    com.ecommerce.user: DEBUG