spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1h}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:14d}

auth:
  refresh-token:
    expiration: ${jwt.refresh-token-expiration}
    cookie-name: refresh_token

logging:
  level:
    com.ecommerce.user: INFO
